actions:
  post-upstream-clone:
    - 'cp dist/libbytesize.spec.in dist/libbytesize.spec'
    - 'sed -i -e "s/@WITH_PYTHON3@/1/g" -e "s/@WITH_GTK_DOC@/1/g" -e "s/@WITH_TOOLS@/1/g" dist/libbytesize.spec'
  create-archive:
    - './autogen.sh'
    - './configure'
    - 'make'
    - 'make local'
    - 'bash -c "ls *.tar*"'

jobs:
- job: copr_build
  metadata:
    targets:
    - fedora-all-aarch64
    - fedora-all-ppc64le
    - fedora-all-x86_64
    - centos-stream-10-aarch64
    - centos-stream-10-ppc64le
    - centos-stream-10-x86_64
    - centos-stream-9-aarch64
    - centos-stream-9-ppc64le
    - centos-stream-9-x86_64
  trigger: pull_request

- job: copr_build
  trigger: commit
  owner: "@storage"
  project: blivet-daily
  branch: main
  preserve_project: true
  actions:
    post-upstream-clone:
      # bump release to 99 to always be ahead of Fedora builds
      - 'bash -c "sed -i -r \"s/Release:(\s*)\S+/Release:     99%{?dist}/\" dist/libbytesize.spec.in"'
      - 'cp dist/libbytesize.spec.in dist/libbytesize.spec'
      - 'sed -i -e "s/@WITH_PYTHON3@/1/g" -e "s/@WITH_GTK_DOC@/1/g" -e "s/@WITH_TOOLS@/1/g" dist/libbytesize.spec'
    create-archive:
      - './autogen.sh'
      - './configure'
      - 'make'
      - 'make local'
      - 'bash -c "ls *.tar*"'

- job: copr_build
  trigger: commit
  owner: "@storage"
  project: udisks-daily
  branch: main
  preserve_project: true
  actions:
    post-upstream-clone:
      # bump release to 99 to always be ahead of Fedora builds
      - 'bash -c "sed -i -r \"s/Release:(\s*)\S+/Release:     99%{?dist}/\" dist/libbytesize.spec.in"'
      - 'cp dist/libbytesize.spec.in dist/libbytesize.spec'
      - 'sed -i -e "s/@WITH_PYTHON3@/1/g" -e "s/@WITH_GTK_DOC@/1/g" -e "s/@WITH_TOOLS@/1/g" dist/libbytesize.spec'
    create-archive:
      - './autogen.sh'
      - './configure'
      - 'make'
      - 'make local'
      - 'bash -c "ls *.tar*"'

- job: propose_downstream
  trigger: release
  dist_git_branches:
    - fedora-all

- job: koji_build
  trigger: commit
  dist_git_branches:
    - fedora-all

- job: bodhi_update
  trigger: commit
  dist_git_branches:
    - fedora-branched

srpm_build_deps:
 - make
 - gcc
 - libtool
 - autoconf
 - automake
 - gmp-devel
 - mpfr-devel
 - pcre2-devel
 - gettext-devel
 - python3-devel
 - gtk-doc

downstream_package_name: libbytesize
specfile_path: dist/libbytesize.spec
